### PR TITLE
Crunchyroll has left beta

### LINKED ISSUE #287: Crunchyroll no longer uses beta.crunchyroll.com (so it's broken on this scrobbler)
beta.crunchyroll.com now resolves to crunchyroll.com. It's been like this for a few months, and as such this tool has been broken for just as long. Could someone please change the code to reflect the correct URL so we can scrobble our anime lists?

### PR DESCRIPTION
**Pull request by MrMamen**
Removed beta from URLs, etc. However gets a CORS-error.

### CODE REVIEW

**Comment by MrMamen** [comment]
Any idea @nyffchanium ?

**Comment by nyffchanium** [comment]
@MrMamen I found the reason for the CORS error. The extension is not requesting access to the new "hostPatterns", thus the requests fail. After disabling and then re-enabling sync for crunchyroll, it worked just fine.
Not sure what to do about that though.

**Comment by noah978** [comment]
Just noting that this solves #210 and looks good to me

**Comment by MrMamen** [comment]
@rafaelgomesxyz Does this make sense?

File: src/common/BrowserStorage.ts [hunk 1]
```diff
@@ -387,6 +391,18 @@ class _BrowserStorage {
 			console.log('Upgrading to v10...');
 		}
 
+		if (version < 11 && this.currentVersion >= 11) {
+			console.log('Upgrading to v11...');
+
+			const { options } = await this.get('options');
+
+			if (options?.services && 'crunchyroll-beta' in options.services) {
+				delete options.services['crunchyroll-beta'];
```
Comment (rafaelgomesxyz) [inline src/common/BrowserStorage.ts:400]: We should copy it to `options.services['crunchyroll']` before deleting it, no? Otherwise the user options for Crunchyroll will be lost (they'll have to re-enable it).

File: src/common/BrowserStorage.ts [hunk 2]
```diff
@@ -397,6 +413,16 @@ class _BrowserStorage {
 	 * They are only separated by type, to make it easier to understand the downgrade process.
 	 */
 	async downgrade(version: number) {
+		if (version > 10 && this.currentVersion <= 10) {
+			console.log('Downgrading to v10...');
+			const values = await this.get('options');
+			const options = values.options;
+			if (options) {
+				delete options.services['crunchyroll'];
```
Comment (rafaelgomesxyz) [inline src/common/BrowserStorage.ts:421]: Same here. On the downgrade, we should copy it to `options.services['crunchyroll-beta']` before deleting it.

**Review by rafaelgomesxyz — CHANGES_REQUESTED** [review]
Hey, sorry it took so long for me to get to this. Just minor comments.

File: src/common/BrowserStorage.ts (hunk 1 above)
Comment (rafaelgomesxyz) [reply src/common/BrowserStorage.ts:400]: I guess this ties back to https://github.com/trakt-tools/universal-trakt-scrobbler/pull/216#issuecomment-1356352686, so the users **should** re-enable it... In that case, disregard this and the comment below.

Still, it would be nice to warn people who have Crunchyroll enabled that they'd have to re-enable it, but that would be too much effort. I'm approving it.

**Review by rafaelgomesxyz — APPROVED** [review]

**Comment by MrMamen** [comment]
The status of the linting is never reported. How come @rafaelgomesxyz ?

**Comment by rafaelgomesxyz** [comment]
@MrMamen Oops, I renamed the action and forgot to update it in the PR merge requirements. Fixed it.
