### PR TITLE
Fix Viaplay profile usage

### LINKED ISSUE #155: Viaplay - Wrong profile
When trying to scrobble (manually) from Viaplay it selects the wrong profile (the owner). 

I'm logged into my own profile but I can't change it.

If I hover over the: 

"History for Viaplay, profile: <insert name>"

it says:

"... swich profiles in the service page"

Where exactly is this "service page" ?

### PR DESCRIPTION
**Pull request by lindvall**
Fixes #155

I've implemented support for Viaplay profiles.

Currently it requires clearing caches after changing profile in Viaplay in order to remove the history of the previously selected profile. Any suggestions are welcome, or simply leave it as is.

### CODE REVIEW

File: src/services/viaplay/ViaplayApi.ts [hunk 1]
```diff
@@ -94,11 +119,13 @@ export interface ViaplayProductUserInfo {
 }
 
 class _ViaplayApi extends ServiceApi {
-	INITIAL_URL = 'https://viaplay.com/requirements';
+	INITIAL_URL = 'https://viaplay.com/';
```
Comment (MrMamen) [inline src/services/viaplay/ViaplayApi.ts:122]: While this may be no longer be correct, it was introduced because of #148
Not sure why you change it, but  perhaps it could be updated to something not broken, like https://viaplay.com/devices ?

**Review by MrMamen — APPROVED** [review]
I'm slightly worried that this may break some regions. The profile change is allerede a known bug #347

File: src/services/viaplay/ViaplayApi.ts (hunk 1 above)
Comment (lindvall) [reply src/services/viaplay/ViaplayApi.ts:122]: The /requirements url was pointing to a 404, which is why I changed it. That may have been a mistake though, as some regions may require a path for the login to work? Let's see if any users experience issues with the change.

**Comment by lindvall** [comment]
Thanks for the approval and the pointer to the catching issue while changing profile! Seems like a rather low priority bug (as you normally only use/sync your own profile).

Hopefully I can solve solve some other issues, and/or implement suggestions in the future.
